name: nodblix
description: Nodblix | Pattern finder of off label usage of drugs to treat numerous health conditions
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0
  shelf: ^1.3.0
  shelf_proxy: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/app_logo_transparent.png
    - assets/by_drug.png
    - assets/by_condition.png
